# Generated by Django 3.0.5 on 2020-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoserver', models.CharField(default='%.%.%.%', max_length=128)),
                ('path', models.CharField(default='/backup/disk1', max_length=256)),
                ('min_free_space_percent', models.IntegerField(default='8')),
                ('active', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.IntegerField(default='0000', primary_key='true', serialize=False, unique='true')),
                ('name', models.CharField(max_length=4, unique='true')),
                ('value', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key='true', serialize=False)),
                ('active', models.IntegerField(default='0')),
                ('name', models.CharField(max_length=64, unique='true')),
                ('videoserver', models.CharField(default='%.%.%.%', max_length=128, unique='true')),
                ('command_line', models.CharField(default='87ea865c-7028-11e2-b34f-00262d167feb', max_length=36)),
                ('video_source', models.CharField(default='286beed5-702a-11e2-b34f-00262d167feb', max_length=36)),
                ('record_time', models.IntegerField(default='180')),
                ('intersection', models.IntegerField(default='2')),
                ('transcode', models.CharField(default='', max_length=256)),
                ('storage', models.CharField(default='177c0150-6ad4-11e2-8e22-00262d167feb', max_length=36)),
                ('schedule', models.CharField(default='308b5899-71bc-11e2-b935-00262d167feb', max_length=36)),
                ('take_time', models.DateField(default='2010-01-01 12:00:00')),
                ('take_videoserver', models.CharField(default='192.168.0.0', max_length=128)),
                ('take_uuid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default='7')),
                ('size_add_hours', models.IntegerField(default='0')),
                ('backup', models.IntegerField(default='0')),
                ('backup_size', models.IntegerField(default='28')),
            ],
        ),
        migrations.CreateModel(
            name='video_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='rtsp://user:password@ip:554/h2', max_length=512)),
                ('options', models.CharField(max_length=512)),
            ],
        ),
    ]
