# Generated by Django 3.0.5 on 2020-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0003_auto_20200415_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='active',
            field=models.IntegerField(db_index=True, default='0'),
        ),
        migrations.AlterField(
            model_name='job',
            name='command_line',
            field=models.CharField(db_index=True, default='87ea865c-7028-11e2-b34f-00262d167feb', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='intersection',
            field=models.IntegerField(db_index=True, default='2'),
        ),
        migrations.AlterField(
            model_name='job',
            name='record_time',
            field=models.IntegerField(db_index=True, default='180'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.CharField(db_index=True, default='308b5899-71bc-11e2-b935-00262d167feb', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.CharField(db_index=True, default='177c0150-6ad4-11e2-8e22-00262d167feb', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_time',
            field=models.DateField(db_index=True, default='2010-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_uuid',
            field=models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.CharField(db_index=True, default='286beed5-702a-11e2-b34f-00262d167feb', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='videoserver',
            field=models.CharField(db_index=True, default='%.%.%.%', max_length=128, unique='true'),
        ),
    ]
