# Generated by Django 3.0.5 on 2020-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0004_auto_20200415_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='take_time',
            field=models.DateField(db_index=True, default='2010-01-01'),
        ),
    ]
