# Generated by Django 3.0.5 on 2020-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0006_remove_job_take_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='take_time',
            field=models.DateTimeField(db_index=True, default='2010-01-01 12:00:00'),
        ),
    ]
