# Generated by Django 3.0.5 on 2020-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0008_remove_job_videoserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='videoserver',
            field=models.CharField(db_index=True, default='%.%.%.%', max_length=128, unique='true'),
        ),
    ]
