# Generated by Django 3.0.5 on 2020-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0009_job_videoserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.IntegerField(default='0000', primary_key=True, serialize=False, unique='true'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False),
        ),
    ]
