# Generated by Django 3.0.5 on 2020-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0011_auto_20200415_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command_line',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(default='/opt/record/record.py -u %url% -t %time% -o %media%', max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='backup',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='backup',
            name='path',
            field=models.CharField(db_index=True, default='/backup/disk1', max_length=256),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.IntegerField(default='0000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storage',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video_source',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False),
        ),
    ]
