# Generated by Django 3.0.5 on 2020-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0012_auto_20200415_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=0, max_length=36, primary_key=True, serialize=False),
        ),
    ]
