# Generated by Django 3.0.5 on 2020-04-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0013_auto_20200415_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
    ]
