# Generated by Django 3.0.5 on 2020-04-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0015_auto_20200415_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
        migrations.AlterField(
            model_name='job',
            name='videoserver',
            field=models.CharField(default='%.%.%.%', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('name', 'videoserver')},
        ),
        migrations.AlterIndexTogether(
            name='job',
            index_together={('active', 'videoserver', 'record_time', 'intersection')},
        ),
    ]
