# Generated by Django 3.0.5 on 2020-04-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0017_auto_20200415_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('year', 'name')},
        ),
    ]
