# Generated by Django 3.0.5 on 2020-04-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0018_auto_20200415_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=1586981361.997903)),
                ('table', models.CharField(max_length=64)),
                ('fields', models.CharField(default='NULL', max_length=500, null=True)),
                ('oldvalues', models.CharField(default='NULL', max_length=500, null=True)),
                ('newvalues', models.CharField(default='NULL', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False)),
                ('calendar', models.CharField(db_index=True, default='0000', max_length=4)),
                ('week_days', models.CharField(db_index=True, default='1111111', max_length=7)),
                ('hours', models.CharField(db_index=True, default='111111111111111111111111', max_length=24)),
                ('event_second_before', models.IntegerField(default='NULL', null=True)),
                ('event_second_after', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smtp_server',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False)),
                ('videoserver', models.CharField(default='%.%.%.%', max_length=128, unique=True)),
                ('active', models.IntegerField(default='1')),
                ('host', models.CharField(default='localhost', max_length=64)),
                ('port', models.IntegerField(default='30000')),
                ('encoding', models.CharField(default='windows-1251', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False)),
                ('videoserver', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=36)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'index_together': {('videoserver', 'job'), ('begin_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, primary_key=True, serialize=False)),
                ('videoserver', models.CharField(default='%.%.%.%', max_length=128)),
                ('path', models.CharField(db_index=True, default='/archive', max_length=256)),
                ('min_free_space_percent', models.FloatField(default='10')),
                ('active', models.IntegerField(default='0')),
            ],
            options={
                'index_together': {('videoserver', 'active')},
            },
        ),
    ]
