# Generated by Django 3.0.5 on 2020-04-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0019_auto_20200415_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(default='308b5899-71bc-11e2-b935-00262d167feb', on_delete=django.db.models.deletion.CASCADE, to='videoserver.Schedule'),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=1586981396.150562),
        ),
    ]
