# Generated by Django 3.0.5 on 2020-04-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0025_auto_20200417_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='command_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Command_line'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Schedule'),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
    ]
