# Generated by Django 3.0.5 on 2020-04-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0028_auto_20200417_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
    ]
