# Generated by Django 3.0.5 on 2020-04-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver', '0030_auto_20200418_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_menu',
            name='sort',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Storage'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoserver.Video_source'),
        ),
    ]
